spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
swagger:
    enabled: true
